# This file is part of AsicVerifier and is released under
# the AGPL-3.0-only License: https://opensource.org/license/agpl-v3/

version: '3.7'
services:
  asicverifier:
    build:
      context: .
      platforms:
        - linux/amd64
      cache_from:
        - type=registry,ref=pipinfitriadi/asicverifier
        - type=registry,ref=niis/xroad-security-server-sidecar:7.0.4
        - type=registry,ref=eclipse-temurin:8-alpine
      cache_to:
        - type=inline
    image: pipinfitriadi/asicverifier
    platform: linux/amd64
    ports:
      - 80:80
    environment:
      - RESTFUL_API_PATH=/asicverifier
