# Copyright (c) Free Software Foundation, Inc. All rights reserved.
# Licensed under the AGPL-3.0-only License. See LICENSE in the project root for license information.

version: '3.7'
services:
  asicverifier:
    build:
      context: .
      platforms:
        - linux/amd64
      cache_from:
        - type=registry,ref=pipinfitriadi/asicverifier
        - type=registry,ref=niis/xroad-security-server-sidecar:7.0.4
        - type=registry,ref=eclipse-temurin:8-alpine
      cache_to:
        - type=inline
    image: pipinfitriadi/asicverifier
    container_name: asicverifier
    platform: linux/amd64
    ports:
      - 80:80
    environment:
      - RESTFUL_API_PATH=/asicverifier
