# This file is part of AsicVerifier and is released under
# the AGPL-3.0-only License: https://opensource.org/license/agpl-v3/

name: CI/CD
on:
  push:
    branches:
      - main
      - feature/python-script
jobs:
  pypi:
    name: PyPI
    runs-on: ubuntu-latest
    environment:
      name: python
      url: https://pypi.org/project/${{ github.event.repository.name }}/
    permissions:
      id-token: write
    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
  docker:
    name: Docker
    needs: pypi
    runs-on: ubuntu-latest
    environment:
      name: docker
      url: https://hub.docker.com/r/${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ github.repository }}
          cache-to: type=inline
          tags: ${{ github.repository }}
          push: true
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
          short-description: ${{ github.event.repository.description }}
