# This file is part of AsicVerifier and is released under
# the AGPL-3.0-only License: https://opensource.org/license/agpl-v3/

name: CI/CD
on:
  pull_request:
  push:
    branches: ['**']
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-z]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+'
jobs:
  venv:
    name: Virtual environment
    if:
      github.ref_type == 'tag' ||
      github.event_name == 'pull_request' ||
      contains('refs/heads/main refs/heads/develop', github.ref)
    runs-on: ubuntu-latest
    steps:
      - name: Cache venv
        id: cache-python-venv
        uses: actions/cache@v3
        with:
          path: venv/
          key: python-venv
      - name: Set up Python
        if: steps.cache-python-venv.outputs.cache-hit != 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install dependencies
        if: steps.cache-python-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv/
          . venv/bin/activate
          pip install --upgrade pip
          pip install build "coverage[toml]"
  lint:
    name: Linter Test
    runs-on: ubuntu-latest
    container:
      image: pipelinecomponents/flake8
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint with flake8
        run: flake8
  unittest:
    name: Unit Test
    needs: venv
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: venv/
          key: python-venv
      - name: Activate venv
        run: |
          . venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Install package
        run: pip install .
      - name: Test
        run: python -m coverage run -m unittest
      - name: Display test coverage
        run: python -m coverage report -m
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Test coverage must be 100% passed!
        if:
          github.ref_type == 'tag' ||
          github.event_name == 'pull_request' ||
          contains('refs/heads/main refs/heads/develop', github.ref)
        run: if [ "$(python -m coverage json -q -o /dev/stdout | jq .totals.percent_covered)" = "100" ]; then exit; else exit 1; fi
  pypi:
    name: PyPI
    needs: [lint, unittest]
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    environment:
      name: python
      url: https://pypi.org/project/${{ github.event.repository.name }}/
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache venv
        uses: actions/cache@v3
        with:
          path: venv/
          key: python-venv
      - name: Build package
        run: |
          . venv/bin/activate
          python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
  docker:
    name: Docker
    # needs: pypi
    runs-on: ubuntu-latest
    environment:
      name: docker
      url: https://hub.docker.com/r/${{ github.repository }}
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Build venv
        uses: docker/build-push-action@v5
        with:
          context: .
          target: venv
          platforms: ${{ matrix.platform }}
          no-cache: true
          tags: ${{ github.repository }}:venv
          load: true
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-contexts: venv=docker-image://${{ github.repository }}:venv
          platforms: ${{ matrix.platform }}
          cache-from: |
            type=registry,ref=${{ github.repository }}
            type=registry,ref=niis/xroad-security-server-sidecar:7.0.4
            type=registry,ref=eclipse-temurin:8-alpine
          cache-to: type=inline
          tags: ${{ github.repository }}
          push: true
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
          short-description: ${{ github.event.repository.description }}
