# This file is part of DataSae and is released under
# the AGPL-3.0-only License: https://opensource.org/license/agpl-v3/

name: Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://hub.docker.com/r/${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}
          cache-from: type=registry,ref=${{ github.repository }}
          cache-to: type=inline
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}
