# This file is part of AsicVerifier and is released under
# the AGPL-3.0-only License: https://opensource.org/license/agpl-v3/

name: Docker
on:
  release:
    types: [published]
jobs:
  release:
    name: Release image
    runs-on: ubuntu-latest
    environment:
      name: docker
      url: https://hub.docker.com/r/${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          cache-from: |
            type=registry,ref=${{ github.repository }}
            type=registry,ref=niis/xroad-security-server-sidecar:7.0.4
            type=registry,ref=eclipse-temurin:8-alpine
          cache-to: type=inline
          tags: ${{ github.repository }}
          push: true
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
          short-description: ${{ github.event.repository.description }}
